SOURCE_PATH = "demo"
DIST_PATH = "__dist"
LOAD_FOLDER = False
LOAD_FOLDER_FLAGS = False
AUTHOR = "Your Name"
DESCRIPTION = "My awesome static website"
GOOGLE_TAG = False # "<tag>"
APP_NAME = "My Website"
DEFAULT_THEME = "dark" # "dark" | "light"
ALLOW_CHANGE_THEME = True
POSTS_ON_INDEX = False # TODO: change this to number
STYLING = True