SOURCE_PATH = "demo"
DIST_PATH = "__dist"
LOAD_FOLDER = False
LOAD_FOLDER_FLAGS = False
AUTHOR = "Michael Sjöberg"
DESCRIPTION = "This is a demo static website built by md2website."
GOOGLE_TAG = False # "<tag>"
APP_NAME = "My Static Website"
ALLOW_CHANGE_THEME = True
POSTS_ON_INDEX = False # TODO: change this to number
STYLING = True